language: ruby
cache: bundler
rvm:
- 2.2.3
branches:
  only:
  - master
install:
  - npm install -g bower
  - bower install
script:
  - rake travis:script --trace
after_success:
  - rake travis:after_success
